# Database Configuration for NexusScan
# Server: SchoolServer (10.176.111.34)
db.url=jdbc:sqlserver://10.176.111.34:1433;databaseName=NexusScan;trustServerCertificate=true
db.user=CS2025b_e_4
db.password=CS2025bE4#23
